language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

before_script:
  - npm run theme
  - npm install
  - npm run build

script:
# enable error reporting to the console
  - set -e
# cleanup ".gh_dist"
  - rm -rf .gh_dist
# clone remote repo to "_site"
  - git clone https://${GH_NAME}:${GH_TOKEN}@github.com/awskrug/eks-workshop.git --branch gh-pages .gh_dist
# dist into ".gh_dist"
  - cd .gh_dist
  - git rm -rf .
  - cp -r ../dist/* ./
# push
  - git config user.email ${GH_EMAIL}
  - git config user.name ${GH_NAME}
  - git add --all
  - git commit -a -m "Travis \#$TRAVIS_BUILD_NUMBER"
  - git push --force origin master