language: node_js

node_js:
  - "10"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm run theme
  - npm install
  - npm run build-kr

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./public
  on:
    branch: gh-pages
